project:
  type: website

website:
  title: "Shallow Learnings"
  navbar:
    right:
      - about.qmd
      - icon: mastodon
        href: https://data-folks.masto.host/@benlindsay
      - icon: github
        href: https://github.com/benlindsay
      - icon: linkedin
        href: https://linkedin.com/in/benjlindsay
  comments:
    giscus:
      repo: "benlindsay/quarto-blog"
      repo-id: "R_kgDOIhZJDw"
      category: "Announcements"
      category-id: "DIC_kwDOIhZJD84CS1B6"
      mapping: "pathname"
      reactions-enabled: true
      loading: "lazy"
      input-position: "bottom"
      theme: "light"
format:
  html:
    theme: cosmo
    css: styles.css
execute:
  freeze: auto
